import 'package:examples/entitu.dart';

List<Vehiculo> listaVehiculosAdicionales = [
  Vehiculo("Ferrari F8 Tributo"),
  Vehiculo("Lamborghini Huracan"),
  Vehiculo("Porsche 911"),
  Vehiculo("Aston Martin DBS Superleggera"),
  Vehiculo("Jaguar F-Type"),
  Vehiculo("Maserati GranTurismo"),
  Vehiculo("Lotus Evora"),
  Vehiculo("McLaren 720S"),
  Vehiculo("Bugatti Chiron"),
  Vehiculo("Koenigsegg Jesko"),
  Vehiculo("Alfa Romeo Giulia"),
  Vehiculo("Bentley Continental GT"),
  Vehiculo("Rolls-Royce Phantom"),
  Vehiculo("Tesla Model S"),
  Vehiculo("Chevrolet Corvette"),
  Vehiculo("Ford Mustang GT"),
  Vehiculo("Dodge Charger"),
  Vehiculo("Jeep Wrangler"),
  Vehiculo("Toyota Supra"),
  Vehiculo("Nissan GT-R"),
  Vehiculo("Subaru Outback"),
  Vehiculo("Volvo XC90"),
  Vehiculo("Audi Q7"),
  Vehiculo("Mercedes-Benz GLE"),
  Vehiculo("BMW X5"),
  Vehiculo("Lexus RX"),
  Vehiculo("Hyundai Palisade"),
  Vehiculo("Kia Telluride"),
  Vehiculo("Mazda CX-9"),
  Vehiculo("Ford Explorer"),
  Vehiculo("Honda Pilot"),
  Vehiculo("Toyota Highlander"),
  Vehiculo("Volkswagen Atlas"),
  Vehiculo("Subaru Ascent"),
  Vehiculo("Chevrolet Traverse"),
  Vehiculo("Buick Enclave"),
  Vehiculo("Cadillac XT6"),
  Vehiculo("GMC Acadia"),
  Vehiculo("Jeep Grand Cherokee"),
  Vehiculo("Land Rover Discovery"),
  Vehiculo("Range Rover Sport"),
  Vehiculo("Audi Q5"),
  Vehiculo("BMW X3"),
  Vehiculo("Mercedes-Benz GLC"),
  Vehiculo("Lexus NX"),
  Vehiculo("Volvo XC60"),
  Vehiculo("Porsche Macan"),
  Vehiculo("Jaguar F-PACE"),
  Vehiculo("Alfa Romeo Stelvio"),
  Vehiculo("Maserati Levante"),
  Vehiculo("Tesla Model X"),
  Vehiculo("Chevrolet Equinox"),
  Vehiculo("Ford Escape"),
  Vehiculo("Honda CR-V"),
  Vehiculo("Toyota RAV4"),
  Vehiculo("Nissan Rogue"),
  Vehiculo("Subaru Forester"),
  Vehiculo("Mazda CX-5"),
  Vehiculo("Volkswagen Tiguan"),
  Vehiculo("Hyundai Tucson"),
  Vehiculo("Kia Sportage"),
  Vehiculo("Jeep Cherokee"),
  Vehiculo("Lexus RX"),
  Vehiculo("BMW X1"),
  Vehiculo("Mercedes-Benz GLA"),
  Vehiculo("Audi Q3"),
  Vehiculo("Volvo XC40"),
  Vehiculo("Ford Bronco"),
  Vehiculo("Land Rover Defender"),
  Vehiculo("Chevrolet Blazer"),
  Vehiculo("Porsche 718 Cayman"),
  Vehiculo("Jaguar E-PACE"),
  Vehiculo("Tesla Model Y"),
  Vehiculo("Toyota Corolla"),
  Vehiculo("Honda Civic"),
  Vehiculo("Ford F-150"),
  Vehiculo("Chevrolet Silverado"),
  Vehiculo("Ram 1500"),
  Vehiculo("Toyota Tacoma"),
  Vehiculo("Nissan Frontier"),
  Vehiculo("Jeep Gladiator"),
  Vehiculo("GMC Sierra"),
  Vehiculo("Honda Ridgeline"),
  Vehiculo("Ford Ranger"),
  Vehiculo("Chevrolet Colorado"),
  Vehiculo("Toyota Tundra"),
  Vehiculo("Nissan Titan"),
  Vehiculo("Tesla Cybertruck"),
  Vehiculo("Audi e-tron"),
  Vehiculo("Jaguar I-PACE"),
  Vehiculo("Porsche Taycan"),
  Vehiculo("Chevrolet Bolt EV"),
  Vehiculo("Nissan Leaf"),
  Vehiculo("Tesla Model 3"),
  Vehiculo("Ford Mustang Mach-E"),
  Vehiculo("Volkswagen ID.4"),
  Vehiculo("Hyundai Kona Electric"),
  Vehiculo("Kia Niro EV"),
];
